services:
  postgres_db:
    image: postgres:15-alpine
    container_name: talentoplus_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talentoplus_api
    environment:
      - ASPNETCORE_URLS=http://+:8080
      # Sobrescribimos la ConnectionString construyéndola con las variables del .env
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      
      # Sobrescribimos la configuración de JWT
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=TalentoPlusAPI
      - Jwt__Audience=TalentoPlusClient
      
      # Sobrescribimos la configuración de Email (SMTP)
      - Smtp__Host=${SMTP_HOST}
      - Smtp__Port=${SMTP_PORT}
      - Smtp__User=${SMTP_USER}
      - Smtp__Password=${SMTP_PASSWORD}
      
      # Sobrescribimos la configuración de OpenAI
      - OpenAi__ApiKey=${OPENAI_API_KEY}

      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db

volumes:
  postgres_data: